M48
; DRILL file {KiCad 7.0.1} date Sun Oct 29 13:19:16 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-29T13:19:16+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.3311Y-2.1591
X3.3311Y-2.8504
X6.6118Y-2.1728
X6.6134Y-2.8633
T2
X4.2382Y-5.0169
X5.6949Y-5.0146
T0
M30
